services:
  localstack:
    image: localstack/localstack-pro
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-docker}"
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
      - "127.0.0.1:443:443"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}
      - PERSISTENCE=0
      - SERVICES=s3,dynamodb,iam,sqs,sts,lambda,cloudwatch,logs
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
